#!/usr/bin/env python3
"""Builds builtin://Libs/IdeHelpersNativeData.lua, the C++ documentation that
upstream's IdeHelpersGenerator.lua merges into its annotations.

Upstream generates this file outside its repository. This reads the same
source: the /// doc comments on the Lua module functions in the vendored
BG3Extender/Lua/Libs (by Norbyte and the bg3se contributors), matched to the
DECLARE_MODULE / MODULE_FUNCTION registrations that export them.

Usage: gen-ide-native-data.py <BG3Extender dir> <output .lua>
"""
import json
import os
import re
import sys

DOC = re.compile(r"^\s*///\s?(.*)$")
SIG = re.compile(r"^[\w:<>,\s\*&]+?\b(\w+)\s*\((.*)\)\s*(const)?\s*$")
DECLARE = re.compile(r"DECLARE_(?:MODULE\((\w+),\s*(\w+)\)|SUBMODULE\((\w+),\s*(\w+),\s*(\w+)\))")
FUNC = re.compile(r"MODULE_(?:NAMED_)?FUNCTION\((?:\"(\w+)\",\s*)?([\w:]+)\)")


def split_params(text):
    params, depth, cur = [], 0, ""
    for ch in text:
        if ch in "<([":
            depth += 1
        elif ch in ">)]":
            depth -= 1
        if ch == "," and depth == 0:
            params.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip():
        params.append(cur)
    names = []
    for p in params:
        p = p.split("=")[0].strip()
        if not p or re.search(r"\blua_State\s*\*", p):
            continue
        # An unnamed parameter keeps its place, named from a /*comment*/ if any.
        comment = re.search(r"/\*\s*(\w+)\s*\*/", p)
        p = re.sub(r"/\*.*?\*/", "", p).strip()
        m = re.search(r"[\s\*&](\w+)$", p)
        if m and not p.endswith(">"):
            names.append(m.group(1))
        else:
            names.append(comment.group(1) if comment else "a%d" % (len(names) + 1))
    return names


def parse_docs(lines):
    """C++ function name -> {summary, export, params} for documented functions."""
    docs = {}
    block = []
    for i, line in enumerate(lines):
        m = DOC.match(line)
        if m:
            block.append(m.group(1))
            continue
        if block:
            text = "\n".join(block)
            block = []
            sig_line = line.strip()
            j = i
            while sig_line.count("(") > sig_line.count(")") and j + 1 < len(lines):
                j += 1
                sig_line += " " + lines[j].strip()
            sig = SIG.match(sig_line.split("{")[0].strip())
            if not sig or "<summary>" not in text and "<param" not in text:
                continue
            summary = re.search(r"<summary>(.*?)</summary>", text, re.S)
            export = re.search(r"<lua_export>(\w+)</lua_export>", text)
            pdesc = dict(re.findall(r"<param name=\"(\w+)\">(.*?)</param>", text, re.S))
            names = split_params(sig.group(2))
            docs[sig.group(1)] = {
                "description": summary.group(1).strip() if summary else "",
                "export": export.group(1) if export else None,
                "params": [{"name": n, "description": pdesc.get(n, "").strip()} for n in names],
            }
    return docs


def main():
    root, out = sys.argv[1], sys.argv[2]
    modules = {}
    libs = os.path.join(root, "Lua", "Libs")
    for name in sorted(os.listdir(libs)):
        if not name.endswith((".inl", ".cpp", ".h")):
            continue
        with open(os.path.join(libs, name), encoding="utf-8", errors="replace") as f:
            lines = f.read().split("\n")
        docs = parse_docs(lines)
        current = None
        for line in lines:
            d = DECLARE.search(line)
            if d:
                if d.group(1):
                    table, role = d.group(1), d.group(2)
                else:
                    table, role = d.group(3) + "." + d.group(4), d.group(5)
                current = (role if role != "Both" else "") + table
                continue
            if "END_MODULE" in line:
                current = None
                continue
            f = FUNC.search(line)
            if f and current:
                cpp = f.group(2).split("::")[-1]
                doc = docs.get(cpp)
                if doc is None:
                    continue
                lua = f.group(1) or doc["export"] or cpp
                entry = {"description": doc["description"], "params": doc["params"]}
                modules.setdefault(current, {"functions": {}})["functions"][lua] = entry
    data = json.dumps({"classes": {}, "modules": modules}, indent=1, sort_keys=True)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("-- Generated by tools/gen-ide-native-data.py from the vendored bg3se sources.\n")
        f.write("return [==[\n" + data + "\n]==]\n")


if __name__ == "__main__":
    main()
