#!/bin/bash
# Regenerates src/vendor/imgui_hdr_shaders.h from the GLSL beside it.
# The header is committed so a build does not need glslc.
set -euo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$HERE/src/vendor/shaders"
OUT="$HERE/src/vendor/imgui_hdr_shaders.h"
{
    echo "// Generated by tools/gen-hdr-shaders.sh from src/vendor/shaders; do not edit."
    echo "#pragma once"
    echo "#include <cstdint>"
    for stage in vert frag; do
        echo "static const uint32_t kHdrComposite_${stage}[] ="
        glslc -O -mfmt=c -o - "$SRC/hdr_composite.$stage"
        echo ";"
    done
} > "$OUT"
echo "wrote $OUT"
