#!/usr/bin/env python3
# Writes src/vendor/system_names.inc: bg3se's ExtSystemType labels and the
# engine class each names, from the DEFINE_SYSTEM lines in the vendored
# headers (bg3se, by Norbyte and the bg3se contributors).
import pathlib, re

root = pathlib.Path(__file__).resolve().parent.parent
defs = root / "vendor/bg3se/BG3Extender/GameDefinitions"
pattern = re.compile(r'DEFINE_SYSTEM\((\w+),\s*"([^"]+)"\)')
pairs = {}
for header in sorted(defs.rglob("*.h")):
    for label, engine in pattern.findall(header.read_text(errors="replace")):
        pairs.setdefault(label, engine)

out = root / "src/vendor/system_names.inc"
lines = ["// Generated by tools/gen-system-names.py; do not edit."]
lines += [f'{{"{label}", "{engine}"}},' for label, engine in sorted(pairs.items())]
out.write_text("\n".join(lines) + "\n")
print(f"{len(pairs)} systems -> {out.relative_to(root)}")
