// Engine code and data bg3le reaches, found in whatever build is running (see resolve.h).
// Generated by tools/make-sigs.py from v4.73.98.727 and v4.76.31.656; each pattern was unique in both.
// Every function returns a link-time offset, or 0 when the target cannot be found: leave the feature off.
#pragma once

#include <cstdint>

namespace bg3le::target {

// EntityStorageContainer::GetEntityStorage(EntityHandle); identical copies exist, so through a call site
std::uintptr_t EntityStorageLookup();
// ls::FixedString's create-from-string
std::uintptr_t FixedStringCreate();
// ecs::EntityWorld::FlushECBs
std::uintptr_t FlushECBs();
// the grid path search
std::uintptr_t PathSearch();
// the surface transform initialiser
std::uintptr_t TransformInit();
// ls::FileReader's destructor
std::uintptr_t FileReaderDtor();
// ls::FileReader's constructor
std::uintptr_t FileReaderCtor();
// ls::TextureManager::LoadTexture(id, streaming, srgb, 1): takes a reference to a tracked texture
std::uintptr_t TextureManagerLoad();
// ls::TextureManager::UnloadTexture(id): drops one
std::uintptr_t TextureManagerUnload();
// RPGStats::Load(paths), from its one call site
std::uintptr_t StatsLoad();
// the Wwise manager's SetSwitch
std::uintptr_t WwiseSetSwitch();
// stats functor parser
std::uintptr_t ParseFunctor();
// the path step
std::uintptr_t PathStep();
// SurfaceManager::AddAction
std::uintptr_t AddAction();
// the state-queue step EoCClient's update calls once a frame (bg3le's client tick)
std::uintptr_t MachineUpdate();
// upstream's ecl::EoCClient::Update(GameTime*), with GameStateMachine::Update inlined
std::uintptr_t ClientAppUpdate();
// esv::GameStateMachine::Update(GameTime*)
std::uintptr_t ServerMachineUpdate();
// the instruction loading the string-keys manager
std::uintptr_t StringKeysManagerLoad();
// stats functor set construction
std::uintptr_t MakeSet();
// stats functor group split
std::uintptr_t SplitGroups();
// ls::ModuleSettings::IsModded
std::uintptr_t IsModded();
// the surface action factory's create
std::uintptr_t CreateAction();
// the Wwise manager's SetState
std::uintptr_t WwiseSetState();
// the instruction loading the GlobalSwitches
std::uintptr_t GlobalSwitchesLoad();
// ecl::GameStateMachine::SetTargetState
std::uintptr_t SetTargetState();
// OsirisVariableHelper::SavegameVisit
std::uintptr_t VariableHelperVisit();
// the LoadModule state's Exit (a bare ret between padding)
std::uintptr_t LoadModuleExit();
// esv::GameServer::UpdateMessagesToSend
std::uintptr_t UpdateMessagesFunc();
std::uintptr_t StateNames();
std::uintptr_t LoadModuleExitSlot();
// the vtable slot holding ClientAppUpdate
std::uintptr_t ClientAppUpdateSlot();
std::uintptr_t CursorControlVtable();
std::uintptr_t WwiseVtable();
std::uintptr_t StateMachineVtable();
std::uintptr_t FunctorsVtable();
std::uintptr_t UpdateMessagesSlot();
std::uintptr_t EoCClient();
// esv::EoCServer*, whose GameStateMachine (+0xa0) holds the server state.
std::uintptr_t EoCServer();
std::uintptr_t StatsGlobal();
std::uintptr_t BoostsManager();
std::uintptr_t ClientLevelManager();
std::uintptr_t TemplatesCache();
std::uintptr_t LevelManager();
std::uintptr_t SurfaceActionFactory();
std::uintptr_t ParserContext();
std::uintptr_t TextureAtlasMap();
std::uintptr_t TemplatesManager();
std::uintptr_t ResourcesGlobal();
// The instruction that loads it; the engine indexes its banks just after.
std::uintptr_t ResourcesGlobalLoad();
std::uintptr_t PathRoots();
std::uintptr_t InputManager();
std::uintptr_t GlobalSwitches();
std::uintptr_t StringKeysManager();
std::uintptr_t TranslatedStringRepository();
// The instruction that loads it; its lock is taken just after.
std::uintptr_t TranslatedStringRepositoryLoad();
// stats functor executors, by FunctorContextType 1..9
std::uintptr_t FunctorExec1();
std::uintptr_t FunctorExec2();
std::uintptr_t FunctorExec3();
std::uintptr_t FunctorExec4();
std::uintptr_t FunctorExec5();
std::uintptr_t FunctorExec6();
std::uintptr_t FunctorExec7();
std::uintptr_t FunctorExec8();
std::uintptr_t FunctorExec9();
// eoc::SpellPrototype::Init
std::uintptr_t SpellPrototypeInit();
// eoc::StatusPrototype::Init
std::uintptr_t StatusPrototypeInit();
// eoc::InterruptPrototype::Init
std::uintptr_t InterruptPrototypeInit();
// the passive loader
std::uintptr_t PassiveLoader();
// the static boost parser
std::uintptr_t BoostParse();
// its callback
std::uintptr_t BoostInvoke();
// its copy
std::uintptr_t BoostCopy();
// its manager
std::uintptr_t BoostManage();
// net::MessageFactory::GetFreeMessage(factory, id)
std::uintptr_t NetGetFreeMessage();
// net::MessageFactory::Register(factory, id, template, growSize, name)
std::uintptr_t NetRegisterMessage();
// net::AbstractPeer::SendMessageSinglePeer, the peers' vtable slot 25
std::uintptr_t NetSendSinglePeer();
// Array<net::Protocol*>::reserve, as the peers grow their protocol lists
std::uintptr_t NetProtocolsReserve();
// the inlined ThreadRegistry index read (mov r14d, fs:disp32), anchored on its function
std::uintptr_t ThreadIndexRead();

}  // namespace bg3le::target
