# Embeds bg3se's builtin Lua scripts (vendor/bg3se/BG3Extender/LuaScripts,
# by Norbyte and the bg3se contributors) so builtin:// paths resolve.
# Usage: cmake -DROOT=<scripts dir> -DOUT=<generated .inc> -P this file
file(GLOB_RECURSE scripts RELATIVE ${ROOT} ${ROOT}/*.lua)
list(SORT scripts)
set(body "")
set(index "")
set(n 0)
foreach(rel ${scripts})
    file(READ ${ROOT}/${rel} hex HEX)
    string(LENGTH "${hex}" hexlen)
    math(EXPR size "${hexlen} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(APPEND body "static const unsigned char kBuiltin${n}[] = {${bytes}0};\n")
    string(APPEND index "    {\"${rel}\", kBuiltin${n}, ${size}},\n")
    math(EXPR n "${n} + 1")
endforeach()
file(WRITE ${OUT}.tmp "// Generated by cmake/embed-builtin-lua.cmake; do not edit.\n${body}\nstatic const BuiltinScript kBuiltinScripts[] = {\n${index}};\n")
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${OUT}.tmp ${OUT})
